### ISSUE TITLE
Error when installing plugin under QGIS 3.4.1

### ISSUE THREAD

**Issue by urskaufmann** [sourcepole/qgis-interlis-plugin#6]
Couldn't load plugin 'interlis' due to an error when calling its classFactory() method 

ImportError: cannot import name 'QCoreApplication' from 'qgis.core' (C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python\qgis\core\__init__.py) 
Traceback (most recent call last):
  File "C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\interlis\__init__.py", line 27, in classFactory
    from .interlis import Interlis
  File "C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\interlis\interlis.py", line 30, in 
    from .algorithms.interlis_provider import InterlisProvider
  File "C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\interlis\algorithms\interlis_provider.py", line 29, in 
    from .ili2pg_algorithms import (Ili2PgSchemaAlgorithm, Ili2PgImportAlgorithm,
  File "C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\interlis\algorithms\ili2pg_algorithms.py", line 32, in 
    from qgis.core import (QgsProcessingAlgorithm,
ImportError: cannot import name 'QCoreApplication' from 'qgis.core' (C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python\qgis\core\__init__.py)

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.1-Madeira Madeira, 383851c597 

Python Path:
C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python
C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python
C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins
C:/2infra/INFRAP~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\2infra\infraprogs\QGIS 3.0\bin\python37.zip
C:\2infra\INFRAP~1\QGIS3~1.0\apps\Python37\DLLs
C:\2infra\INFRAP~1\QGIS3~1.0\apps\Python37\lib
C:\2infra\infraprogs\QGIS 3.0\bin
C:\2infra\INFRAP~1\QGIS3~1.0\apps\Python37
C:\2infra\INFRAP~1\QGIS3~1.0\apps\Python37\lib\site-packages
C:\2infra\INFRAP~1\QGIS3~1.0\apps\Python37\lib\site-packages\win32
C:\2infra\INFRAP~1\QGIS3~1.0\apps\Python37\lib\site-packages\win32\lib
C:\2infra\INFRAP~1\QGIS3~1.0\apps\Python37\lib\site-packages\Pythonwin
C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python
C:\Users\kau\AppData\Roaming\QGIS\QGIS3\profiles\test\python\plugins\DigitizingTools\tools

**Comment by mrtwister3142** [comment]
Change
`from qgis.core import QCoreApplication`
to 
`from qgis.PyQt.QtCore import QCoreApplication`
in
ili2c_algorithms.py
ili2gpkg_algorithms.py
ili2pg_algorithms.py
and it works.

**Comment by tpo** [comment]
Under QGIS 3.22 this plugin can be installed and run. So maybe this bug is not a bug any more with current QGIS versions and can be closed?

**Comment by urskaufmann** [comment]
That's long time and many releases ago...
Seems it works with 3.34.10, but I don't know the original constellation anymore

**Comment by tpo** [comment]
@urskaufmann - are you still using the plugin? Or asked differently: would you allow me to ping you on updates so I can get feedback that the service still works as expected?

**Comment by urskaufmann** [comment]
no, I do not use it. I work with TEKSI / QGEP for wastewater-XTF-files or with Modelbaker...

**Comment by tpo** [comment]
thanks a lot for the info @urskaufmann !
